[package]
name = "wasmer-examples/angular-wasmer-starter"
version = "0.2.3"
description = "Angular (with SSR support!) Wasmer starter package"
readme = "README.md"
repository = "https://github.com/wasmer-examples/angular-wasmer-starter"

[dependencies]
"wasmer/winterjs" = "^0.3.4"

[fs]
"/web" = "dist/winterjs"

[[command]]
name = "script"
module = "wasmer/winterjs:winterjs"
runner = "wasi"

[command.annotations.wasi]
main-args = ["--mode", "cloudflare", "/web"]
